In [12]:
import pandas as pd

In [13]:
df_true = pd.read_csv('datasets/Fake_Real_News_Dataset/True.csv')
df_fake = pd.read_csv('datasets/Fake_Real_News_Dataset/Fake.csv')

In [14]:
df_fake.head()

                                               title  ...               date
0   Donald Trump Sends Out Embarrassing New Year’...  ...  December 31, 2017
1   Drunk Bragging Trump Staffer Started Russian ...  ...  December 31, 2017
2   Sheriff David Clarke Becomes An Internet Joke...  ...  December 30, 2017
3   Trump Is So Obsessed He Even Has Obama’s Name...  ...  December 29, 2017
4   Pope Francis Just Called Out Donald Trump Dur...  ...  December 25, 2017

[5 rows x 4 columns]

In [15]:
df_true.head()

                                               title  ...                date
0  As U.S. budget fight looms, Republicans flip t...  ...  December 31, 2017
1  U.S. military to accept transgender recruits o...  ...  December 29, 2017
2  Senior U.S. Republican senator: 'Let Mr. Muell...  ...  December 31, 2017
3  FBI Russia probe helped by Australian diplomat...  ...  December 30, 2017
4  Trump wants Postal Service to charge 'much mor...  ...  December 29, 2017

[5 rows x 4 columns]

In [16]:
df_fake.isnull().sum()
df_true.isnull().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [17]:
df_fake['label'] = 'Fake'
df_true['label'] = 'True'

In [18]:
df = pd.concat([df_true, df_fake], ignore_index=True)
df.head()
df.tail()

                                                   title  ... label
44893  McPain: John McCain Furious That Iran Treated ...  ...  Fake
44894  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...  ...  Fake
44895  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...  ...  Fake
44896  How to Blow $700 Million: Al Jazeera America F...  ...  Fake
44897  10 U.S. Navy Sailors Held by Iranian Military ...  ...  Fake

[5 rows x 5 columns]

In [19]:
df['label'].value_counts()

label
Fake    23481
True    21417
Name: count, dtype: int64

In [20]:
#ELIMINAR CODIGO HTML

In [21]:
import warnings
from bs4 import BeautifulSoup, MarkupResemblesLocatorWarning

In [22]:
# Ejemplo de texto con HTML
ejemplo_html = '<p>This is a ‹b›breaking</b› news ‹a href="http://example.com"›story</a></p>'
print( "Texto original:", ejemplo_html)

Texto original: <p>This is a ‹b›breaking</b› news ‹a href="http://example.com"›story</a></p>

In [23]:
texto_limpio = BeautifulSoup(ejemplo_html,'html.parser').get_text()
texto_limpio

'This is a ‹b›breaking'

In [24]:
def strip_text(text):
    """Elimina etiquetas html"""
    return BeautifulSoup(text, 'html.parser').get_text()

In [25]:
df.iloc[0]['text'][:300]

'WASHINGTON (Reuters) - The head of a conservative Republican faction in the U.S. Congress, who voted this month for a huge expansion of the national debt to pay for tax cuts, called himself a “fiscal conservative” on Sunday and urged budget restraint in 2018. In keeping with a sharp pivot under way '

In [26]:
import re

In [27]:
#Eliminar las url
def del_urls(text):
    return re.sub(r'https?://\S+','', text)

In [28]:
ejemplo_url = "Breaking news about the economy https://www.example.com/news check it out"
del_urls(ejemplo_url)

'Breaking news about the economy  check it out'

In [29]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [30]:
def del_punctuation(text):
    text = text.lower()
    text = text.translate(str.maketrans('','', string.punctuation))
    # Eliminamos también Las comillas tipográficas y otros caracteres especiales Unicode
    # que no están incluidos en string.punctuation
    text= re.sub(r'[\u2018\u2019\u201C\u201D\u2013\u2014\u2026]', '',text)
    return text

In [31]:
# Ejemplo
ejemplo = "BREAKING NEWS! The President said:'No comment'."
print("Original:", ejemplo)
print("Procesado:", del_punctuation(ejemplo))

Original: BREAKING NEWS! The President said:'No comment'.
Procesado: breaking news the president saidno comment

In [32]:
import nltk
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /Users/enrique/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/enrique/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/enrique/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [33]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 
from nltk.stem import PorterStemmer

In [34]:
# stopwords en inglés
stop_words = set(stopwords.words('english'))
print (f"Número de stopwords: {len (stop_words)} ")
print (f"\nAlgunos ejemplos: {(list(stop_words) [:20])} ")

Número de stopwords: 198

Algunos ejemplos: ['did', "he'll", 'needn', 'only', 'very', 'during', "we'd", 'whom', 'from', 'has', "aren't", "you'll", "i'd", 'same', "it'd", 'been', 'where', "needn't", 'our', "they're"]

In [35]:
#funcion de Stemmer
stemmer = PorterStemmer()
palabras = ["running", "runs", "ran", "playing", "played", "investigation", "investigating"]
for palabra in palabras:
    print(f' {palabra:20s} -> {stemmer.stem(palabra)} ')

 running              -> run
 runs                 -> run
 ran                  -> ran
 playing              -> play
 played               -> play
 investigation        -> investig
 investigating        -> investig

In [36]:
# Ejemplo completo: tokenizar, eliminar stopwords y aplicar stemming
ejemplo = "The president was running an investigation into the reported claims"
print ("Texto original:", ejemplo)
# 1. Tokenizar (dividir en palabras)
tokens = word_tokenize(ejemplo.lower())
print ("InTokens:", tokens)
# 2. Eliminar stopwords
tokens_filtrados = [t for t in tokens if t not in stop_words]
print("\nSin stopwords:", tokens_filtrados)
# 3. Aplicar stemming
tokens_stem = [stemmer. stem(t) for t in tokens_filtrados]
print("\nCon stemming: ", tokens_stem)

Texto original: The president was running an investigation into the reported claims
InTokens: ['the', 'president', 'was', 'running', 'an', 'investigation', 'into', 'the', 'reported', 'claims']

Sin stopwords: ['president', 'running', 'investigation', 'reported', 'claims']

Con stemming:  ['presid', 'run', 'investig', 'report', 'claim']

In [37]:
'''
Aplica todas las transformaciones de preprocesamiento sobre un texto:
0. Eliminar prefijos de fuentes
1. Eliminar etiquetas HTML
2. Eliminar URLs
3. Convertir a minúsculas
4. Eliminar signos de puntuación
5. Tokenizar
6. Eliminar stopwords
7. Aplicar stemming
'''

def preprocesar_texto(text):
    # 0. Eliminar prefijos de fuente tipo "CIUDAD (Reuters) -" o "CIUDAD (AP) -"
    text = re.sub(r'^[A-ZÁÉÍÓÚÑÜ\s,.-]+\(([^)]+)\)\s*[-–—]\s*','',text)    
    #2. Eliminar URLs
    text = del_urls(text)
    # 1. Eliminar etiquetas HTML
    text = strip_text(text)
    #3. Convertir a minúsculas
    #4. Eliminar signos de puntuación
    text = del_punctuation(text)
    #5. Tokenizar
    tokens = word_tokenize(text)
    # 6. ELiminar stopwords
    tokens = [t for t in tokens if t not in stop_words]
    # 7. Stemming
    stemmer = PorterStemmer ()
    tokens = [stemmer. stem(t) for t in tokens]
    return ' '.join( tokens)

In [38]:
#Seleccionamos 1000 noticias al azar
df_sample = df.sample(n=1000, random_state=42)

In [39]:
df_sample['text_clean'] = df_sample['text'].apply(preprocesar_texto)

In [40]:
df_sample[['text','label','text_clean']].head()

                                                    text  ...                                         text_clean
22216  Donald Trump s White House is in chaos, and th...  ...  donald trump white hous chao tri cover russia ...
27917  Now that Donald Trump is the presumptive GOP n...  ...  donald trump presumpt gop nomine time rememb c...
25007  Mike Pence is a huge homophobe. He supports ex...  ...  mike penc huge homophob support exgay convers ...
1377   SAN FRANCISCO (Reuters) - California Attorney ...  ...  california attorney gener xavier becerra said ...
32476  Twisted reasoning is all that comes from Pelos...  ...  twist reason come pelosi day especi 2006 promi...

[5 rows x 3 columns]

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
'''
•fit(): aprende el vocabulario a partir de los textos de entrenamiento.
•transform() : transforma los textos en vectores numéricos usando el vocabulario aprendido.
'''

'\n•fit(): aprende el vocabulario a partir de los textos de entrenamiento.\n•transform() : transforma los textos en vectores numéricos usando el vocabulario aprendido.\n'

In [54]:
ejemplo_textos = [
"president signs new law today",
"new study shows results today"]

vectorizer_ejemplo = CountVectorizer()
vectorizer_ejemplo.fit(ejemplo_textos)
vectorizer_ejemplo.get_feature_names_out()

array(['law', 'new', 'president', 'results', 'shows', 'signs', 'study',
       'today'], dtype=object)

In [56]:
#Transformar texto a vectores
vectores_ejemplo = vectorizer_ejemplo.transform(ejemplo_textos)
#vizualizacion
pd.DataFrame(vectores_ejemplo.toarray(), columns=vectorizer_ejemplo.get_feature_names_out(),index=["Noticia 1", "Noticia 2"])

           law  new  president  results  shows  signs  study  today
Noticia 1    1    1          1        0      0      1      0      1
Noticia 2    0    1          0        1      1      0      1      1